####################################
# This file can be used with Skaffold (https://github.com/GoogleContainerTools/skaffold) to
# build and deploy Fission to Kubernetes cluster.
# Skaffold version v1.10.1 is used for this configuration.
############## Usage ##############
# Skaffold CLI should be installed on your machine.
# For building & deploying to Cloud Provider
# $ skaffold config set default-repo vishalbiyani (vishalbiyani - should be your registry/Dockerhub handle)
# $ `skaffold run`
# For building & deploying to Kind cluster use Kind profile
# $ `skaffold run -p kind`
####################################
apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
    - image: fission
      context: .
      docker:
        dockerfile: build/bundle/Dockerfile
        buildArgs:
          TARGET: bundle
          PKG: github.com/fnlize/fnlize
    - image: fetcher
      docker:
        dockerfile: build/fetcher/Dockerfile
        buildArgs:
          TARGET: fetcher
          PKG: github.com/fnlize/fnlize
    - image: preupgradechecks
      docker:
        dockerfile: build/preupgradechecks/Dockerfile
        buildArgs:
          TARGET: preupgradechecks
          PKG: github.com/fnlize/fnlize

deploy:
  helm:
    flags:
      install: ["--timeout=3m", "--debug", "--create-namespace"]
    releases:
      - name: fission
        chartPath: ./charts/fission-all
        valuesFiles:
          - ./charts/fission-all/values.yaml
        namespace: "fission"
        artifactOverrides:
          image: "fission"
          preUpgradeChecksImage: "preupgradechecks"
          fetcher.image: "fetcher"
        setValues:
          namespace: fission
          repository: "index.docker.io"
          routerServiceType: LoadBalancer
          pruneInterval: 60
          fetcher.imageTag: ""
          imageTag: ""
          prometheus.enabled: false
        wait: true
        recreatePods: false
        packaged: null
        imageStrategy:
          fqn: null
          helm: null

profiles:
  - name: kind
    patches:
      - op: replace
        path: /deploy/helm/releases/0/setValues/repository
        value: ""
      - op: replace
        path: /deploy/helm/releases/0/setValues/routerServiceType
        value: "NodePort"
  - name: kind-ci
    patches:
      - op: replace
        path: /deploy/helm/releases/0/setValues/repository
        value: ""
      - op: replace
        path: /deploy/helm/releases/0/setValues/pruneInterval
        value: 1
      - op: replace
        path: /deploy/helm/releases/0/setValues/routerServiceType
        value: "NodePort"
      - op: replace
        path: /deploy/helm/releases/0/setValues/prometheus.enabled
        value: true
