name: Server Build Image

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  fnlize-image:
    name: fnlize image
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: ["builder", "fetcher", "preupgradechecks", "cli", "bundle"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Building image
        uses: docker/build-push-action@v2
        with:
          file: build/${{ matrix.image }}/Dockerfile
          push: true
          context: .
          tags: fnlize/${{ matrix.image }}:latest
          build-args: |
            PKG=github.com/fission/fission
            TARGET=${{ matrix.image }}
